### ISSUE TITLE
Equipment set not changing

### ISSUE THREAD

**Issue by Scrapheap** [TekNoLogic/Crossdresser#7]
Often times when I change specs the equipment does not change with it.
I do have a fix for the code:

function f:ACTIVE_TALENT_GROUP_CHANGED()
    if lastgroup == GetActiveTalentGroup() then return end

```
lastgroup = GetActiveTalentGroup()
local name = dbpc[lastgroup]
Debug("Talent switch detected", lastgroup)
if not name then return end

local found
for i=1,GetNumEquipmentSets() do if GetEquipmentSetInfo(i) == name then found = true end end
if not found then return Print("Cannot find set:", name) end

Debug("Equipping set", name)

repeat
until UnitCastingInfo("player") == nil

EquipmentManager_EquipSet(name)
```

end

**Comment by villiv** [comment]
Another sync (or latency) issue I think. So my guess is:

```
if ( EquipmentSetContainsLockedItems(name) --[[or UnitCastingInfo("player")]] ) then
    UIErrorsFrame:AddMessage(ERR_CLIENT_LOCKED_OUT, 1.0, 0.1, 0.1, 1.0);
    return;
end

UseEquipmentSet(name);
```

Yes, it's from Bliz's code. =)

**Comment by Zidomo** [comment]
Yes, that single line change fix (first mentioned in issue 4 here long ago, see below) resolves the "sometimes doesn't equip set" issue which has been a problem with this mod for going on a year and a half.

Without the message spam (but similar to the last one above), just change line 65 in the existing Crossdresser.lua from:

EquipmentManager_EquipSet(name)

to:

UseEquipmentSet(name)

That's it. Don't add a semicolon at the end. This problem was first brought up here in issue 4 (https://github.com/tekkub/Crossdresser/issues/4) on Oct. 9/2009. That single line change above was first mentioned in that ticket & fixes the problem; it works 100% of the time here in WoW 4.1 live.
